Raya/sdk updates
smarty/smartystreets-javascript-sdk pull request #58
Opened 2022-11-01 20:43 UTC by raywray

click up cards: 
- https://app.clickup.com/t/3xtjpa4
- https://app.clickup.com/t/3xtjqdv
- https://app.clickup.com/t/3xtjpqh

2022-11-04 22:54 UTC, camiblanch commented
Is this compatible with the retry sender in `HttpSender.js`?

2022-11-07 16:54 UTC, raywray commented
@camiblanch I think I can just delete the retry in the HTTP sender, but maybe we should look over it together later today to make sure?

2022-11-07 22:37 UTC, camiblanch requested changes

2022-11-07 22:37 UTC, camiblanch commented on package.json
> +  "nyc": "^15.1.0"
What is the purpose of this package, `nyc`?

2022-11-07 22:37 UTC, camiblanch commented on tests/fixtures/FailingSender.js
> +	send(request) {
Do you think we should include the request here since it's not used? I like the idea of showing that it usually takes a request, but we just don't use it in this mock function so maybe that's a reason to keep it here? What do you think?

2022-11-07 22:37 UTC, camiblanch commented on src/util/FakeSleeper.js
> +		// return new Promise(resolve => setTimeout(resolve, ms));
Does this comment need to stay here?

2022-11-07 22:37 UTC, camiblanch commented on src/util/Sleeper.js
> +class Sleeper {
This is really cool how you set the whole sleeper thing up. Makes it so easy to test!

2022-11-07 22:37 UTC, camiblanch commented on src/util/FakeSleeper.js
> +class FakeSleeper {
I wonder if this should be relocated to be in the tests directory since it's only used for testing purposes. What do you think? Maybe have a directory in the tests directory specifically for mock/fake classes?

2022-11-07 22:37 UTC, camiblanch commented on src/util/FakeSleeper.js
> +class FakeSleeper {
I'm looking at the `mock_sender.js` in the fixtures directory and it looks like it's similar to this. Let's group them together.

2022-11-07 22:37 UTC, camiblanch commented on src/Response.js
> +	constructor (statusCode, payload, error = undefined, headers = undefined) {
I think defaulting to undefined is redundant because I think if those parameters aren't set they are undefined anyways. Is that right?

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +				if(response.headers) {
- [ ] add space between `if` and `(`

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +				await this.rateLimitBackOff(secondsToBackoff)
- [x] add semicolon to end of line

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +				await this.backoff(i)
- [x] add semicolon to end of line

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +					if (Number.isInteger(response.headers["Retry-After"])) {
Can you create a variable to store `response.headers["Retry-After"]` so it isn't repeated between this line and the next?

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +					if (Number.isInteger(response.headers["Retry-After"])) {
- [x] Create variable

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +				let secondsToBackoff = 10;
This is listed as seconds, but is passed to the sleeper which takes milliseconds. 

- [x] pass milliseconds to the sleeper

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +					if (Number.isInteger(response.headers["Retry-After"])) {
Here's another idea, of how it could be worded. I think either is fine

```
const retryAfterHeader = response?.headers?.["Retry-After"];
if (retryAfterHeader) {
	secondsToBackoff = retryAfterHeader;
}
```

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +		let response = this.inner.send(request);
Does this need to have an `await` added? Since the `send` method being called returns a promise 

- [x] add `await`

2022-11-07 22:37 UTC, camiblanch commented on src/RetrySender.js
> +			response = this.inner.send(request);
This should also have an `await` added

- [x] add `await`

2022-11-07 23:31 UTC, camiblanch approved these changes

2022-11-07 23:31 UTC, merged